/**
 * Payload Admin Layout
 *
 * Auto-generated by Payload, but MODIFIED to include the required
 * `serverFunction` prop for Payload CMS 3.x / Next.js 16 compatibility.
 *
 * If Payload regenerates this file, you'll need to re-add the serverFunction wrapper.
 * See: https://payloadcms.com/docs/getting-started/installation
 */
import config from '@payload-config';
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts';
import type { ServerFunctionClient } from 'payload';
import type React from 'react';
import { importMap } from './admin/importMap';
import './custom.scss';

type Args = {
	children: React.ReactNode;
};

const serverFunction: ServerFunctionClient = async (args) => {
	'use server';

	return handleServerFunctions({
		...args,
		config,
		importMap,
	});
};

const Layout = ({ children }: Args) =>
	RootLayout({
		children,
		config,
		importMap,
		serverFunction,
	});

export default Layout;
